# Generated by Django 2.0.7 on 2018-07-26 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('avi', 'm1v', 'mov', 'movie', 'mp4', 'mpa', 'mpe', 'mpeg', 'mpg', 'qt', 'webm'))]),
        ),
    ]
